### ISSUE TITLE
learn-javascript

### ISSUE THREAD

**Issue by achmadk** [aisyahwsn/Project-React-Native#1]
Baik, Mbak. Terima kasih sudah bersedia meng-install `yarn` sama `node` di laptop Mbak. Terima kasih juga masih bersedia untuk melanjutkan mentoring ini. Sebagai selingan, ada mentor yang murid bimbingannya udah nggak aktif lagi, padahal dari mentor sudah memperkenalkan diri.

Karena Mbak sudah mempelajari bahasa pemrograman swift, saya coba membandingkan swift dengan javascript supaya Mbak bisa lebih mudah memahami javascript. Berikut saya kenalkan sedikit informasi mengenai javascript, `node`, sama `yarn`.

Javascript merupakan bahasa pemrograman yang memungkinkan sebuah halaman/aplikasi web menjadi lebih dinamis. Salah satu contohnya header navigasi pada situs LAPOR (lapor.go.id). awalnya header navigasinya transparan. Begitu di-scroll ke bawah, header-nya berada di atas dan berwarna putih. Adapun fungsi javascript lainnya yaitu mendapatkan/mengirimkan data dari/ke server lain, mengetahui posisi pengguna menggunakan geolocation, login otomatis menggunakan akun google, dan sebagainya.

Seiring dengan berjalannya waktu, javascript ternyata bisa dijalankan di server, sebagai alternatifnya PHP, ruby, dan bahasa pemrograman server side lainnya. Javascript yang dapat dijalankan di server ini lebih familiar disebut `nodejs`.

`yarn` bisa dikatakan sebagai `cocoapods`-nya di javascript. Sebenarnya setelah menginstall node, secara default sudah ada packaging manager yang bernama `npm`. `yarn` dipakai saat ini karena punya banyak keuntungan ketika nantinya mulai membuat aplikasi sederhana menggunakan react maupun react-native.

Untuk memulai belajar javascript, mungkin bisa bikin repo github dulu Mbak, misalnya `learn-javascript`.
1. Tonton video [berikut](https://www.youtube.com/watch?v=lFyqd9xrRTY).
2. Ubahlah sintaks swift yang dituliskan Mas Chris ke dalam bahasa pemrograman javascript dengan ketentuan sebagai berikut:
  a. `import UIKit` dihapus
  b. `var` pada swift diganti dengan `let`. Di javascript, pendeklarasian variabel yang memungkinkan nilainya dapat berubah, gunakan `var` atau `let`.
  c. `let` pada swift diganti dengan `const`. jika sudah ada variabel yang menggunakan `const` dan ditentukan nilai awalnya, nilai dari variabel tersebut tidak dapat diganti.
  d. Fungsi `print` pada swift diganti dengan `console.log`. Bisa juga dicoba dengan `console.warn` maupun `console.error`.
  e. Pada saat pendeklarasian variabel di javascript, tidak perlu dituliskan tipe datanya seperti di swift.

Hasil konversi swift ke javascript dapat dilakukan dengan 2 cara.
1. Dituliskan per baris ke dalam console sebuah browser. Misalnya buka Google Chrome, kemudian klik kanan -> inspect. Setelah itu, buka tab console, dilanjutkan tulis masing-masing baris kode.
2. Salin hasil konversinya ke dalam file index.js. Buka command line, kemudian arahkan direktori ke folder index.js tersebut berada. Setelah itu, ketikkan node index.js.
Kedua screenshot hasil dari cara tersebut diunggah ke repo

Mohon juga jawab beberapa pertanyaan berikut.
1. Apa yang terjadi jika suatu variabel menggunakan let yang nilai awalnya bertipe data string, kemudian diganti nilainya jadi nilai yang bertipe data number?
2. Apa yang terjadi jika suatu variabel menggunakan const yang nilai awalnya bertipe data boolean, kemudian diganti nilainya jadi nilai yang bertipe data number?
3. Jelaskan perbadaan antara console.log, console.warn, dan console.error?
Pertanyaan dan jawaban dapat diunggah ke repo dengan nama file questions.md

**Comment by aisyahwsn** [comment]
Baik, mas. Ini saya sertakan jawabannya https://github.com/aisyahningsi/learn-javascript/tree/master
